name: 🚧 Feature request
description: Suggest a new feature or other enhancement.
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "Please check [closed/rejected issues](https://github.com/thoukydides/homebridge-homeconnect/issues?q=is%3Aissue) and [discussions](https://github.com/thoukydides/homebridge-homeconnect/discussions) for any previous requests to implement similar functionality. Requests for additional configuration options to disable functionality, or inappropriate use of HomeKit services/characteristics, will be rejected."

  - type: markdown
    attributes:
      value:  "If programs or options are missing for your appliance then check whether they are supported by the [Home Connect API](https://api-docs.home-connect.com/programs-and-options). If not, then [contact the Home Connect Developer team](https://developer.home-connect.com/support/contact) to request their addition instead of raising an issue here."

  - type: textarea
    id: description
    attributes:
      label: Description of Enhancement
      description: "Please provide a clear and concise description of your proposed improvement. Include specific use cases or examples where this enhancement would be beneficial."
    validations:
      required: true

  - type: textarea
    id: hcmap
    attributes:
      label: Home Connect Mapping
      description: "Please suggest how the requested functionality can be supported using the options, states, settings, events, and other features, of the [Home Connect API](https://api-docs.home-connect.com/)."
    validations:
      required: false

  - type: textarea
    id: hapmap
    attributes:
      label: HomeKit Mapping
      description: "Please suggest how the requested functionality can be supported using the Apple-defined services and characteristics listed in the [HomeKit Accessory Protocol Specification (Non-Commercial Version)](https://developer.apple.com/apple-home/)."
    validations:
      required: false

  - type: input
    id: appliance
    attributes:
      label: Home Connect Appliance(s)
      description: "If this enhancement relates to a specific appliance then please provide the manufacturer, type, and model number. These details can be found in the Apple Home app or the Homebridge log file."
      placeholder: "e.g. Siemens Oven HB678GBS6B/50"
    validations:
      required: false

- type: markdown
  attributes:
    value: |
      **Important Notes:**
      - Feature requests must align with HomeKit's intended functionality and Home Connect API capabilities.
      - Features outside the scope of HomeKit or Home Connect API are unlikely to be implemented.
      - Detailed, actionable suggestions, are more likely to be considered.